---
title: "Tables for Gender Paper"
date: "`r Sys.Date()`"
output:
  pdf_document:
    extra_dependencies: ["dcolumn", "booktabs", "caption", "float"]
    toc: yes
    toc_depth: 6
    keep_tex: yes
---

\captionsetup[table]{labelformat=empty}


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F, fig.retina = 4)
```

```{r message=FALSE, warning=FALSE}
# Libraries
pacman::p_load(haven, estimatr, extrafont, texreg, janitor, hrbrthemes, xtable, papeR, tidyverse, compareGroups, Hmisc, skimr)
```

\newpage

# Main Tables

```{r}
# Student Data
df_stu <- 
  read_dta(here::here("data", "stu_admin_all_latest.dta")) %>%
  left_join(read_dta(here::here("data/reservation_new.dta")), by = "stdid") %>% 
  mutate(
    reservation = dplyr::recode(reservation, "Non-reservation" = 0L, "Reservation" = 1L, .default = NA_integer_),
  )


df <- 
  read_dta(here::here("data", "all_appended.dta")) %>% 
  distinct(stdid, course_name, facid, .keep_all = T) %>% 
  left_join(
    df_stu %>% 
      select(stdid, classid, department_id, reservation, caste, ea_stud_group_criteria, grade),
    by = "stdid"
  ) %>%
  filter(ea_stud_group_criteria == 2, grade == 2) %>%
  left_join(read_dta(here::here("data/fac_covariates.dta")), by = "facid")


# fixing for course cleaning done by sk in sep 2021
df <-
  df %>% 
  left_join(
    read_dta(here::here("data/students_clean.dta")),
    by = c("department_id", "course_name")
  ) %>% 
  mutate(
    course_name = if_else(!is.na(course_clean_sk), course_clean_sk, course_name)
  ) %>%
  distinct(stdid, course_name, facid, .keep_all = T)


# grade data after veda's work
df_grades <-
  read_dta(here::here("data/30jan2022/df_gradefac.dta")) %>% 
  filter(facid != "") %>%
  left_join(df_stu %>% select(stdid, department_id, reservation, caste, b_i_jeemain_score, b_math_g1_score, b_physics_g1_score, e_math_g3_score, e_physics_g3_score, elite), by = "stdid") %>%
  left_join(read_dta(here::here("data/controls.dta")), by = "stdid") %>%
  left_join(read_dta(here::here("data/fac_covariates.dta")), by = "facid") %>% 
  arrange(department_id, course_name, course_grade_clean) %>% 
  group_by(department_id, course_name) %>% 
  mutate(
    course_rank = (scale(course_grade_clean) %>% pnorm() * 100) %>% as.vector
  ) %>% 
  ungroup() %>%
  mutate(
    father_college = if_else(father_ed_ind > 3 & !is.na(father_ed_ind), 1L, 0L),
    father_college = if_else(is.na(father_ed_ind), NA_integer_, father_college),
    mother_college = if_else(mother_ed_ind > 3 & !is.na(mother_ed_ind), 1L, 0L),
    mother_college = if_else(is.na(mother_ed_ind), NA_integer_, mother_college),
    ses = ses %>% as.integer(),
    female = female %>% as.integer(),
    univcode = str_sub(department_id, 1, 5)
  ) %>%
  relocate(department_id, course_name, stdid, course_rank) %>% 
  rename(reservation_stu = reservation, fac_teaching = fac_tpi_score7_z) %>% 
  filter(univcode != "IR036")
  

# df_grades %>% drop_na() %>% glimpse()
# df_grades %>% select(contains("college"))

rm(df)

df_mechanism <-
  df_grades %>%
  select(facid, reservation_fac, department_id, course_name, stdid, course_rank) %>% 
  left_join(
    read_dta(here::here("data/fac_covars1.dta")), 
    by = "facid"
  ) %>% 
  left_join(read_dta(here::here("data/fac_covars3.dta")), by = "facid") %>% 
  left_join(read_dta(here::here("data/fac_covars2.dta")), by = "facid") %>% 
  mutate_at(vars(starts_with("weekly")), ~ parse_number(.)) %>%
  mutate(
    total_time =
      pmap_dbl(
        select(., weekly_hours_teaching_related, weekly_hours_advising_students, weekly_hours_research, weekly_hours_part_time_job, weekly_hours_administrative),
        ~ sum(c(...), na.rm = TRUE)
      ),
    fac_prop_research = (weekly_hours_research * 10) / total_time
  )


# filtering to all faculty surveyed during the endline phase who were also mentioned by students
facdata_mentions <-
  read_dta(here::here("data/all_appended.dta")) %>%
  filter(tag > 1) %>%  # endline only
  left_join(df_stu %>% select(stdid, department_id), by = "stdid") %>%  # get dep_id
  select(facid, department_id) %>% 
  count(facid, department_id) %>% 
  arrange(facid, desc(n)) %>% 
  distinct(facid, .keep_all = T) %>% 
  select(-n) %>% 
  left_join(read_dta(here::here("data/endline_faculty_data_final.dta")), by = "facid")


df_grades %>% 
  distinct(facid, .keep_all = T) %>% 
  get_dupes(facid, reservation_fac)
```


```{r, results='asis', eval=F}
lm1 <-
  df_grades %>%
  mutate(fe_var = str_c(department_id, course_name, sep = "_")) %>%
  lm_robust(course_rank ~ female * fac_female, data = ., fixed_effects = ~ fe_var, se_type = "stata")

lm2 <-
  df_grades %>%
  mutate(fe_var = str_c(department_id, course_name, sep = "_")) %>%
  lm_robust(course_rank ~ female * fac_female + reservation_stu + female + age + father_college + mother_college + fac_associate_professor + fac_professor + fac_yearsinhighed + fac_highest_degree_phd + fac_highest_degree_phd_in_prog + fac_degree_college_elite + reservation_fac, data = ., fixed_effects = ~ fe_var, se_type = "stata")

lm3 <-
  df_grades %>%
  mutate(fe_var = str_c(department_id, course_name, sep = "_")) %>%
  lm_robust(course_rank ~ female * fac_female + fac_associate_professor + fac_professor + fac_yearsinhighed + fac_highest_degree_phd + fac_highest_degree_phd_in_prog + fac_degree_college_elite + reservation_fac, data = ., fixed_effects = ~ fe_var + stdid, se_type = "stata")

lm4 <-
  df_grades %>%
  mutate(fe_var = str_c(department_id, course_name, sep = "_")) %>%
  lm_robust(course_rank ~ female * fac_female, data = ., fixed_effects = ~ fe_var + stdid + facid, se_type = "stata")

lm5 <-
  df_grades %>%
  mutate(
    fe_var = str_c(department_id, course_name, sep = "_"),
    class_fe_var = str_c(fe_var, facid, sep = "_")
  ) %>%
  lm_robust(course_rank ~ female * fac_female, data = ., fixed_effects = ~ fe_var + stdid + class_fe_var, se_type = "stata")

texreg(list(lm1, lm2, lm3, lm4, lm5), custom.note = "%stars", stars = c(0.01, 0.05, 0.1), include.ci = F, dcolumn = T, booktabs = T, float.pos = "H", caption = "", digits = 2, include.nclust = F, include.rsquared = F, include.adjrs = F, include.rmse = F)
```


```{r}
df_grades %>%
  mutate(fe_var = str_c(department_id, course_name, sep = "_")) %>%
  lm_robust(course_rank ~ female * fac_female + stdid, data = ., fixed_effects = ~ fe_var, se_type = "stata") %>% 
  summary()
```

```{r}
df_grades %>% 
  filter(stdid == "H6XTT") %>% 
  glimpse()
```

