---
title: "Tables for Teacher-like-me Paper"
date: "`r Sys.Date()`"
output:
  pdf_document:
    extra_dependencies: ["dcolumn", "booktabs", "caption", "float"]
    toc: yes
    toc_depth: 6
    keep_tex: yes
---

\captionsetup[table]{labelformat=empty}


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F, fig.retina = 4)
```

```{r message=FALSE, warning=FALSE}
# Libraries
pacman::p_load(haven, estimatr, extrafont, texreg, janitor, hrbrthemes, xtable, papeR, tidyverse, compareGroups, Hmisc, skimr)
```

\newpage

# Main Tables

```{r}
# Student Data
df_stu <- 
  read_dta(here::here("data", "stu_admin_all_latest.dta")) %>%
  left_join(read_dta(here::here("data/reservation_new.dta")), by = "stdid") %>% 
  mutate(
    reservation = dplyr::recode(reservation, "Non-reservation" = 0L, "Reservation" = 1L, .default = NA_integer_),
  )


df <- 
  read_dta(here::here("data", "all_appended.dta")) %>% 
  distinct(stdid, course_name, facid, .keep_all = T) %>% 
  left_join(
    df_stu %>% 
      select(stdid, classid, department_id, reservation, caste, ea_stud_group_criteria, grade),
    by = "stdid"
  ) %>%
  filter(ea_stud_group_criteria == 2, grade == 2) %>%
  left_join(read_dta(here::here("data/fac_covariates.dta")), by = "facid")


# fixing for course cleaning done by sk in sep 2021
df <-
  df %>% 
  left_join(
    read_dta(here::here("data/students_clean.dta")),
    by = c("department_id", "course_name")
  ) %>% 
  mutate(
    course_name = if_else(!is.na(course_clean_sk), course_clean_sk, course_name)
  ) %>%
  distinct(stdid, course_name, facid, .keep_all = T)


# grade data after veda's work
df_grades <-
  read_dta(here::here("data/30jan2022/df_gradefac.dta")) %>% 
  filter(facid != "") %>%
  left_join(df_stu %>% select(stdid, department_id, reservation, took_jee, b_i_jeemain_score, b_math_g1_score, b_physics_g1_score, e_math_g3_score, e_physics_g3_score, elite, b_ct_score, b_ql_score, b_rr_score, b_testtype), by = "stdid") %>%
  left_join(read_dta(here::here("data/controls.dta")), by = "stdid") %>%
  left_join(read_dta(here::here("data/fac_covariates.dta")), by = "facid") %>% 
  arrange(department_id, course_name, course_grade_clean) %>% 
  group_by(department_id, course_name) %>% 
  mutate(
    course_rank = (scale(course_grade_clean) %>% pnorm() * 100) %>% as.vector
  ) %>% 
  ungroup() %>%
  mutate(
    father_college = if_else(father_ed_ind > 3 & !is.na(father_ed_ind), 1L, 0L),
    father_college = if_else(is.na(father_ed_ind), NA_integer_, father_college),
    mother_college = if_else(mother_ed_ind > 3 & !is.na(mother_ed_ind), 1L, 0L),
    mother_college = if_else(is.na(mother_ed_ind), NA_integer_, mother_college),
    ses = ses %>% as.integer(),
  ) %>%
  relocate(department_id, course_name, stdid, course_rank) %>% 
  rename(reservation_stu = reservation, fac_teaching = fac_tpi_score7_z, semester = semester_clean) %>% 
  inner_join(readxl::read_xlsx(here::here("data/introductory_courses.xlsx")), by = "course_name")

rm(df)
```



\newpage

# Current Table 5.4: Regressions for Quality of Instruction by Reservation Faculty

```{=latex}
\begin{table}[H]
\begin{center}
\begin{tabular}{l D{.}{.}{5.4} D{.}{.}{5.4} D{.}{.}{5.4} D{.}{.}{5.4}}
\toprule
 & \multicolumn{1}{c}{I} & \multicolumn{1}{c}{II} & \multicolumn{1}{c}{III} & \multicolumn{1}{c}{IV} \\
\midrule
Reservation faculty               & 1.44^{**} & 1.52^{**} & 1.33^{**}  & 1.34^{**}  \\
                                  & (0.58)    & (0.59)    & (0.57)     & (0.56)     \\
Associate professor               &           & 0.57      & 1.25       & 1.27       \\
                                  &           & (0.75)    & (0.83)     & (0.82)     \\
Professor                         &           & 1.46      & 2.97^{**}  & 3.18^{**}  \\
                                  &           & (0.93)    & (1.35)     & (1.32)     \\
Experience in years               &           & -0.02     & -0.02      & -0.01      \\
                                  &           & (0.05)    & (0.05)     & (0.05)     \\
Highest degree is PhD             &           &           & -2.37^{**} & -2.55^{**} \\
                                  &           &           & (1.19)     & (1.17)     \\
Highest degree is PhD in progress &           &           & -0.75      & -0.94      \\
                                  &           &           & (0.80)     & (0.82)     \\
Degree college elite              &           &           & 0.37       & 0.31       \\
                                  &           &           & (0.59)     & (0.59)     \\
Female                            &           &           &            & 1.09^{*}   \\
                                  &           &           &            & (0.57)     \\
\midrule
Num. obs.                         & 37767     & 37716     & 37716      & 37716      \\
N Clusters                        & 498       & 496       & 496        & 496        \\
\bottomrule
\multicolumn{5}{l}{\scriptsize{$^{***}p<0.01$; $^{**}p<0.05$; $^{*}p<0.1$}}
\end{tabular}
\caption{}
\label{table:coefficients}
\end{center}
\end{table}
```

\newpage

# New Table

```{r, results='asis'}
lm1 <-
  df_grades %>%
  mutate(year2 = if_else(semester >= 3, 1L, 0L)) %>%
  mutate(fe_var = str_c(department_id, course_name, sep = "_")) %>%
  lm_robust(course_rank ~ reservation_fac * year2 + fac_associate_professor + fac_professor + fac_yearsinhighed + fac_highest_degree_phd + fac_highest_degree_phd_in_prog + fac_degree_college_elite + fac_female, data = ., fixed_effects = ~ stdid + fe_var, se_type = "stata", clusters = facid)

lm2a <-
  df_grades %>%
  mutate(semester = as_factor(semester)) %>%
  mutate(fe_var = str_c(department_id, course_name, sep = "_")) %>%
  lm_robust(course_rank ~ reservation_fac * semester + fac_associate_professor + fac_professor + fac_yearsinhighed + fac_highest_degree_phd + fac_highest_degree_phd_in_prog + fac_degree_college_elite + fac_female, data = ., fixed_effects = ~ stdid + fe_var, se_type = "stata", clusters = facid)

lm2b <-
  df_grades %>%
  mutate(semester = as_factor(semester)) %>%
  mutate(fe_var = str_c(department_id, course_name, sep = "_")) %>%
  lm_robust(course_rank ~ reservation_fac * semester + fac_associate_professor + fac_professor + fac_yearsinhighed + fac_highest_degree_phd + fac_highest_degree_phd_in_prog + fac_degree_college_elite + fac_female - reservation_fac, data = ., fixed_effects = ~ stdid + fe_var, se_type = "stata", clusters = facid)

lm3 <-
  df_grades %>%
  mutate(advanced = if_else(introductory == 0, 1L, 0L)) %>%
  mutate(fe_var = str_c(department_id, course_name, sep = "_")) %>%
  lm_robust(course_rank ~ reservation_fac * advanced + fac_associate_professor + fac_professor + fac_yearsinhighed + fac_highest_degree_phd + fac_highest_degree_phd_in_prog + fac_degree_college_elite + fac_female, data = ., fixed_effects = ~ stdid + fe_var, se_type = "stata", clusters = facid)


knitreg(list(lm1, lm2b, lm2a, lm3), custom.note = "%stars", stars = c(0.01, 0.05, 0.1), include.ci = FALSE, dcolumn = TRUE, booktabs = TRUE, float.pos = "H", caption = "", digits = 2, include.nclust = F, include.rsquared = F, include.adjrs = F, include.rmse = F, omit.coef = "(^advanced)|(^year2)|(^semester)", custom.model.names = c("Year 2", "Semesters V2", "Semesters V1", "Advanced"))
```



